name: Regression Suite

on:
  push

jobs:
  regression_matrix:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Python ${{ matrix.python-version }} x64
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy cython
          python -m pip install --upgrade -r $GITHUB_WORKSPACE/requirements.txt
          python -m pip install --upgrade -r $GITHUB_WORKSPACE/tests/requirements.txt
          python setup.py build_ext --inplace

      - name: "Start Memcached Instance"
        run: |
            docker run -d --name my-memcached \
                       -p 11211:11211 \
                       memcached \
                       -m 16

      - name: "Start MongoDB Instance"
        run: |
            docker run -d --name test-mongo \
                       -p 27017:27017 \
                       -e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
                       -e MONGO_INITDB_ROOT_PASSWORD=secret \
                       mongo:latest

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Run Regression Tests
        run: python -m coverage run -m pytest 
        env:
          AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;"
          MINIO_END_POINT: "s3.eu-west-2.amazonaws.com"
          MONGO_CONNECTION: "mongodb://mongoadmin:secret@localhost:27017"
          MONGO_DATABASE: opteryx
          GCP_PROJECT_ID: mabeldev
          MYSQL_USER: '${{ secrets.MYSQL_USER }}'
          MYSQL_PASSWORD: '${{ secrets.MYSQL_PASSWORD }}'
          POSTGRES_USER: '${{ secrets.POSTGRES_USER }}'
          POSTGRES_PASSWORD: '${{ secrets.POSTGRES_PASSWORD }}'

      - name: Check Coverage
        run: python -m coverage report --include=opteryx/** --fail-under=95 -m

      - name: "Upload coverage to Codecov"
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false